[build]
  publish="build/"
  
[context.production]
  publish = "build/"

[template.environment]
  REACT_APP_HOME_CATEGORIES_IDS="Category Ids"
  BIGCOMMERCE_STOREFRONT_API_URL="BigCommerce API Endpoint"
  BIGCOMMERCE_STORE_API_CLIENT_ID="BigCommerce API Id"
  BIGCOMMERCE_STORE_API_TOKEN="BigCommerce API Token"
  BIGCOMMERCE_STORE_API_URL="BigCommerce Store API Url"
  BIGCOMMERCE_STORE_HASH="BigCommerce Store Hash"

  BIGCOMMERCE_STOREFRONT_API_TOKEN="BigCommerce API Token"